name: Meterian Scanner

on:
  push:
    branches-ignore:
      - '**meterian-bot/pr**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  meterian_scan:
    name: Meterian client scan
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Meterian Scanner
        uses: MeterianHQ/meterian-github-action@v1.0.17
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          oss: true
          autofix_security: safe
          autofix_with_pr: true
